export interface FaIcon {
  label: string;
  cls: string;
}

export const FA_ICONS: FaIcon[] = [
  // Social / Brands
  { label: 'GitHub',         cls: 'fa-brands fa-github' },
  { label: 'X / Twitter',   cls: 'fa-brands fa-x-twitter' },
  { label: 'Twitter',        cls: 'fa-brands fa-twitter' },
  { label: 'Instagram',      cls: 'fa-brands fa-instagram' },
  { label: 'Facebook',       cls: 'fa-brands fa-facebook' },
  { label: 'LinkedIn',       cls: 'fa-brands fa-linkedin' },
  { label: 'YouTube',        cls: 'fa-brands fa-youtube' },
  { label: 'Twitch',         cls: 'fa-brands fa-twitch' },
  { label: 'Discord',        cls: 'fa-brands fa-discord' },
  { label: 'Reddit',         cls: 'fa-brands fa-reddit' },
  { label: 'TikTok',         cls: 'fa-brands fa-tiktok' },
  { label: 'Snapchat',       cls: 'fa-brands fa-snapchat' },
  { label: 'Pinterest',      cls: 'fa-brands fa-pinterest' },
  { label: 'Tumblr',         cls: 'fa-brands fa-tumblr' },
  { label: 'Patreon',        cls: 'fa-brands fa-patreon' },
  { label: 'Spotify',        cls: 'fa-brands fa-spotify' },
  { label: 'Steam',          cls: 'fa-brands fa-steam' },
  { label: 'PlayStation',    cls: 'fa-brands fa-playstation' },
  { label: 'Xbox',           cls: 'fa-brands fa-xbox' },
  { label: 'Mastodon',       cls: 'fa-brands fa-mastodon' },
  { label: 'Bluesky',        cls: 'fa-brands fa-bluesky' },
  { label: 'DeviantArt',     cls: 'fa-brands fa-deviantart' },
  { label: 'ArtStation',     cls: 'fa-brands fa-artstation' },
  { label: 'Behance',        cls: 'fa-brands fa-behance' },
  { label: 'Dribbble',       cls: 'fa-brands fa-dribbble' },
  { label: 'SoundCloud',     cls: 'fa-brands fa-soundcloud' },
  { label: 'Bandcamp',       cls: 'fa-brands fa-bandcamp' },
  { label: 'Itch.io',        cls: 'fa-brands fa-itch-io' },
  { label: 'Medium',         cls: 'fa-brands fa-medium' },
  { label: 'Vimeo',          cls: 'fa-brands fa-vimeo' },
  { label: 'Telegram',       cls: 'fa-brands fa-telegram' },
  { label: 'WhatsApp',       cls: 'fa-brands fa-whatsapp' },
  { label: 'Slack',          cls: 'fa-brands fa-slack' },
  { label: 'GitLab',         cls: 'fa-brands fa-gitlab' },
  { label: 'Bitbucket',      cls: 'fa-brands fa-bitbucket' },
  { label: 'Stack Overflow', cls: 'fa-brands fa-stack-overflow' },
  { label: 'Dev.to',         cls: 'fa-brands fa-dev' },
  { label: 'WordPress',      cls: 'fa-brands fa-wordpress' },
  { label: 'Etsy',           cls: 'fa-brands fa-etsy' },
  { label: 'Shopify',        cls: 'fa-brands fa-shopify' },
  { label: 'Apple',          cls: 'fa-brands fa-apple' },
  { label: 'Android',        cls: 'fa-brands fa-android' },
  { label: 'Windows',        cls: 'fa-brands fa-windows' },
  { label: 'Linux',          cls: 'fa-brands fa-linux' },
  { label: 'Python',         cls: 'fa-brands fa-python' },
  { label: 'JavaScript',     cls: 'fa-brands fa-js' },
  { label: 'Node.js',        cls: 'fa-brands fa-node-js' },
  { label: 'React',          cls: 'fa-brands fa-react' },
  { label: 'Docker',         cls: 'fa-brands fa-docker' },
  { label: 'Google',         cls: 'fa-brands fa-google' },
  // Solid — general
  { label: 'Link',           cls: 'fa-solid fa-link' },
  { label: 'Globe',          cls: 'fa-solid fa-globe' },
  { label: 'Email',          cls: 'fa-solid fa-envelope' },
  { label: 'Phone',          cls: 'fa-solid fa-phone' },
  { label: 'Location',       cls: 'fa-solid fa-location-dot' },
  { label: 'Star',           cls: 'fa-solid fa-star' },
  { label: 'Heart',          cls: 'fa-solid fa-heart' },
  { label: 'Bookmark',       cls: 'fa-solid fa-bookmark' },
  { label: 'Music',          cls: 'fa-solid fa-music' },
  { label: 'Camera',         cls: 'fa-solid fa-camera' },
  { label: 'Video',          cls: 'fa-solid fa-video' },
  { label: 'Code',           cls: 'fa-solid fa-code' },
  { label: 'Gamepad',        cls: 'fa-solid fa-gamepad' },
  { label: 'Graduation',     cls: 'fa-solid fa-graduation-cap' },
  { label: 'Briefcase',      cls: 'fa-solid fa-briefcase' },
  { label: 'Coffee',         cls: 'fa-solid fa-mug-hot' },
  { label: 'Dollar',         cls: 'fa-solid fa-dollar-sign' },
  { label: 'Shop',           cls: 'fa-solid fa-cart-shopping' },
  { label: 'User',           cls: 'fa-solid fa-user' },
  { label: 'Users',          cls: 'fa-solid fa-users' },
  { label: 'Comment',        cls: 'fa-solid fa-comment' },
  { label: 'Share',          cls: 'fa-solid fa-share-nodes' },
  { label: 'RSS',            cls: 'fa-solid fa-rss' },
  { label: 'News',           cls: 'fa-solid fa-newspaper' },
  { label: 'Book',           cls: 'fa-solid fa-book' },
  { label: 'Pen',            cls: 'fa-solid fa-pen' },
  { label: 'Laptop',         cls: 'fa-solid fa-laptop' },
  { label: 'Mobile',         cls: 'fa-solid fa-mobile-screen' },
  { label: 'Image',          cls: 'fa-solid fa-image' },
  { label: 'Film',           cls: 'fa-solid fa-film' },
  { label: 'Headphones',     cls: 'fa-solid fa-headphones' },
  { label: 'Microphone',     cls: 'fa-solid fa-microphone' },
  { label: 'Trophy',         cls: 'fa-solid fa-trophy' },
  { label: 'Award',          cls: 'fa-solid fa-award' },
  { label: 'Palette',        cls: 'fa-solid fa-palette' },
  { label: 'Paintbrush',     cls: 'fa-solid fa-paintbrush' },
  { label: 'Dice',           cls: 'fa-solid fa-dice' },
  { label: 'Dice D20',       cls: 'fa-solid fa-dice-d20' },
  { label: 'Crown',          cls: 'fa-solid fa-crown' },
  { label: 'Rocket',         cls: 'fa-solid fa-rocket' },
  { label: 'Flag',           cls: 'fa-solid fa-flag' },
  { label: 'Home',           cls: 'fa-solid fa-house' },
  { label: 'Store',          cls: 'fa-solid fa-store' },
  { label: 'Ghost',          cls: 'fa-solid fa-ghost' },
  { label: 'Robot',          cls: 'fa-solid fa-robot' },
  { label: 'Sun',            cls: 'fa-solid fa-sun' },
  { label: 'Moon',           cls: 'fa-solid fa-moon' },
  { label: 'Fire',           cls: 'fa-solid fa-fire' },
  { label: 'Lightning',      cls: 'fa-solid fa-bolt' },
  { label: 'Snowflake',      cls: 'fa-solid fa-snowflake' },
  { label: 'Gem',            cls: 'fa-solid fa-gem' },
  { label: 'Leaf',           cls: 'fa-solid fa-leaf' },
  { label: 'Tree',           cls: 'fa-solid fa-tree' },
  { label: 'Seedling',       cls: 'fa-solid fa-seedling' },
  { label: 'Paw',            cls: 'fa-solid fa-paw' },
  { label: 'Cat',            cls: 'fa-solid fa-cat' },
  { label: 'Dog',            cls: 'fa-solid fa-dog' },
  { label: 'Dragon',         cls: 'fa-solid fa-dragon' },
  { label: 'Pizza',          cls: 'fa-solid fa-pizza-slice' },
  { label: 'Beer',           cls: 'fa-solid fa-beer-mug-empty' },
  { label: 'Wine',           cls: 'fa-solid fa-wine-glass' },
  { label: 'Map',            cls: 'fa-solid fa-map-location-dot' },
  { label: 'Compass',        cls: 'fa-solid fa-compass' },
  { label: 'Plane',          cls: 'fa-solid fa-plane' },
  { label: 'Car',            cls: 'fa-solid fa-car' },
  { label: 'Bicycle',        cls: 'fa-solid fa-bicycle' },
  { label: 'Key',            cls: 'fa-solid fa-key' },
  { label: 'Shield',         cls: 'fa-solid fa-shield-halved' },
  { label: 'Sparkles',       cls: 'fa-solid fa-wand-sparkles' },
  { label: 'Atom',           cls: 'fa-solid fa-atom' },
  { label: 'Flask',          cls: 'fa-solid fa-flask' },
  { label: 'Brain',          cls: 'fa-solid fa-brain' },
  { label: 'Eye',            cls: 'fa-solid fa-eye' },
  { label: 'Scroll',         cls: 'fa-solid fa-scroll' },
  { label: 'Theater Masks',  cls: 'fa-solid fa-masks-theater' },
  { label: 'Skull',          cls: 'fa-solid fa-skull' },
  { label: 'Infinity',       cls: 'fa-solid fa-infinity' },
  { label: 'Rainbow',        cls: 'fa-solid fa-rainbow' },
  { label: 'Umbrella',       cls: 'fa-solid fa-umbrella' },
];
